language: python
python:
    - 2.7
before_install:
    - date -u
    - uname -a
    - lsb_release -a
    - sudo apt-get -qq update
    - sudo apt-get install build-essential python-dev swig libasound2-dev
    - swig -version
    - sudo usermod -a -G audio $USER
install:
    - pip install coveralls
    - python setup.py install
script:
    - sudo -E su $USER -c 'nosetests --with-coverage --cover-package=midi'
after_success:
    - coveralls
